### ISSUE TITLE
ReferenceError: React is not defined

### ISSUE THREAD

**Issue by jadbox** [yolkjs/yolk-todomvc#5]
In the bundle generated Yolk App.js code from Babel, I see this:
```
Yolk.render(React.createElement(Main, { state: state.asObservable }), document.querySelector('#container'));
```

Although I don't see anywhere were React is actually being included in the Todo example. FYI, I'm using the Bower Yolk package for my example.

**Comment by garbles** [comment]
Does making [this](https://github.com/yolkjs/yolk#using-jsx) change help?

**Comment by jadbox** [comment]
That worked! I should have looked over the README more closely ;)
