### ISSUE TITLE
State.asObservable sharing

### ISSUE THREAD

**Issue by jadbox** [yolkjs/yolk-todomvc#7]
Without having asObservable being a shared reply, you can have issues where the raw transform function gets pulled into the state stream if you have more than one subscriber on it.

Something like this is needed:
```
this.asObservable = this.updates.scan((state, operation) => operation(state)).shareReplay(1);
```

**Comment by garbles** [comment]
You're right. Fixed in https://github.com/yolkjs/yolk-todomvc/commit/d03d0d5fb32f277e4380f153c679360743b93ed7
