### ISSUE TITLE
State based on ImmutableJS

### ISSUE THREAD

**Issue by jadbox** [yolkjs/yolk-todomvc#8]
I know a little bit about Immutable, but as I'm building our app on Yolk- I'm finding that it seems to add more complexity than it provides in benefits. The todo example doesn't really show this. I find that constantly pushing values back into the datastore using ```Immutable.fromJS(value)``` gets noisy, as well as unmarshaling arrays/lists from the state using ```toJS()```. 

Basically, what are the benefits with using Immutable with Yolk? What are the pros/cons of not using it? I'm just looking to understand this methodology better in context to reactive states.

**Comment by garbles** [comment]
If your stores are immutable, you probably don't want to just call `toJS` every time you ask for a new value.

Anyway, the benefits for using it with Yolk are the same as they would be with React/Cycle or any other library that offers one-way data flow. I suggest you ask that question on Stackoverflow or something.

**Comment by jadbox** [comment]
Okay, I think I understand it now. Thanks for your time!
